### ISSUE TITLE
sesiones paraleles del viernes 6 y sábado 7

### ISSUE THREAD

**Issue by mariapoveda** [OKFN-Spain/jpd16#13]
¿se podrían poner en dos columnas para indicar que son sesiones paralelas? En esas aparece el lugar.

En las que ya están a dos columnas no tengo claro en qué salas son, por ejemplos "Los papeles de Panamá" y "datatables workshop".

**Comment by flowsta** [comment]
Por cuestiones responsivas, he puesto todo en una sola columna. He añadido información de a qué sala se refiere cada sección. Se entiende mejor ahora?

**Comment by mariapoveda** [comment]
ok
