### ISSUE TITLE
Color enlaces en programa

### ISSUE THREAD

**Issue by flowsta** [OKFN-Spain/jpd16#15]
He puesto enlaces en el programa y no se ven bien, habrá que cambiarlos @martgnz 
http://jpd16.okfn.es/#programa

**Comment by martgnz** [comment]
Ya está hecho.

Si estáis trabajando en la web por favor leed un poco el css, no cuesta tanto:
- link: enlace para fondo blanco, en color negro
- link--inverse: enlace para fondo oscuro, en color blanco

También para @MaiSalEsc
