### ISSUE TITLE
[proposal] Redirigir de http://periodismodatos.okfn.es/ a http://jpd16.okfn.es/

### ISSUE THREAD

**Issue by iamsortiz** [OKFN-Spain/jpd16#2]
Buenas,

Buscando por jornadas de periodismo de datos me aparecía la URL http://periodismodatos.okfn.es/ y si mal no recuerdo en alguna publicación hacíais referencia a dicha URL.

**Sería interesante redirigir a los usuarios de http://periodismodatos.okfn.es/ a http://jpd16.okfn.es/**

Si quereis mantener la web antigua podríais colgarla en http://jpd15.okfn.es/ por ejemplo.

Saludos.

**Comment by martgnz** [comment]
Algún cambio? He visto un landing, pero no una redirección

**Comment by flowsta** [comment]
el tema es no perder las urls antiguas, que están en periodismodatos.okfn.es. Para eso habría que hacer redirects pero no ha sido posible. Alguna idea nueva?

**Comment by martgnz** [comment]
No se puede meter lo de periodismodatos.okfn.es en jpd15.okfn.es entonces?

**Comment by martgnz** [comment]
Creo que lo mejor será cerrar esta issue con un wontfix. @flowsta ?
